### ISSUE TITLE
issue in querying data

### ISSUE THREAD

**Issue by ravibhooshan** [fifemon/graphql-test-source#1]
Hi,
I am trying to use this plugin very first time. I am using Grafana 7.3.4.
II am getting below error while try to run a query. This query gives proper result in GraphqlV2 UI.
"Cannot query field 'submissions' on type 'QueryV2'."

 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/11981903/154615094-25d58a02-b61e-429f-a469-32df7e04ca11.png">

**Comment by retzkek** [comment]
First, you have the wrong repository, you wanted https://github.com/fifemon/graphql-datasource
Second, `submissions` is a field in the default placeholder query, so it sounds like you haven't entered your query correctly. Paste it here and I'll take a look.

**Comment by ravibhooshan** [comment]
Thanks for your response.
I am using correct repo, I posted this question  her by mistake. DO you want me to move this query to that repo.

Here is the query I am using.
query {
  openShiftProjects:submissions(name: "sas|ingest") {
    name
      supportGroup
      assignmentGroup
      managedByGroup
  }
}

**Comment by retzkek** [comment]
No it's fine, I see your problem.

```
openShiftProjects:submissions(name: "sas|ingest")
```

Is querying a field named `submissions` and assigning it the alias `openShiftProjects`, which is almost certainly not what you want. I assume the field in your API is just called `openShiftProjects`, so try

```graphql
query {
openShiftProjects(name: "sas|ingest") {
name
supportGroup
assignmentGroup
managedByGroup
}
}
```

I'd encourage you to test out your queries in something like GraphiQL first.

**Comment by ravibhooshan** [comment]
I was using the same query, you have provided, I just added submission to test.
I am still getting same error.
Is it something to do with V2 of Graphql.

**Comment by ravibhooshan** [comment]
Thanks for your help. Its working.
